packages:
  - 'packages/*'
  - 'packages/typing-game/*'
  - 'examples/*'
  - 'comparisons/*'
  - 'internal/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - '@effect/platform-browser@4.0.0-rc.112'
  - '@effect/platform-node-shared@4.0.0-rc.112'
  - '@effect/platform-node@4.0.0-rc.112'
  - '@effect/vitest@4.0.0-rc.112'
  - effect@4.0.0-rc.112

overrides:
  '@mapbox/jsonlint-lines-primitives': 2.0.2
  '@types/node': 26.4.0
  effect: 4.0.0-rc.112
  '@effect/platform-browser': 4.0.0-rc.112
  '@effect/platform-node': 4.0.0-rc.112
  '@effect/platform-node-shared': 4.0.0-rc.112
  '@effect/vitest': 4.0.0-rc.112
  'monaco-editor>dompurify': 3.4.14
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vitest: 4.1.11
  vite-plus: 0.3.0
  '@vitest/coverage-v8': 4.1.11
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
